version: '3.8'

services:
  my_sql:
    image: mysql:latest
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      TZ: Asia/Tokyo
    volumes:
      - data-volume:/var/lib/mysql
      - ./test_db:/docker-entrypoint-initdb.d
volumes:
  data-volume: